### ISSUE TITLE
[RERACT] 코드 구조 변경

### ISSUE THREAD

**Issue by euzl** [euzl/GitHub-Search-API-Android#16]
## 설명
코드에서 고쳐야 할 부분이 있음

## TODO
- [ ] `adapter` 초기화 위치 변경
- [ ] 검색 api 실행 후 데이터만 교체
- [ ] `service`에서 callback 위치 변경 ㅎㅎㅎ(error <-> failure 반대로 되어있음)
- [ ] `callback` 중복으로 호출되는지 확인

## 참고사항
fix인지 refactor인지 헷갈림..
