### ISSUE TITLE
[FEAT] 검색 결과 목록으로 표시

### ISSUE THREAD

**Issue by euzl** [euzl/GitHub-Search-API-Android#3]
## 설명
#2 에서 받은 결과를 #1 에 `recyclerView`로 표시한다.

## TODO
- [x] `adapter` 생성
- [x] `item_layout` 생성 (목록에 뭘 표시할 지 정하기)
- [x] 로딩 시간 -> ProgressBar 표시
- [x] Toast 메시지 : 몇 건이 조회 됐는지 안내 (0건 => 조회결과가 없습니다.)

## 참고사항
아이템 클릭은 안 하는 상황으로 가정
