### ISSUE TITLE
[UPDATE] 컬리 색상 적용

### ISSUE THREAD

**Issue by euzl** [euzl/GitHub-Search-API-Android#5]
## 설명
컬리 색상 적용

## TODO
- [x] colors.xml 에 컬리 색상 추가
- [x] themes.xml 에 색상 적용
- [x] edit text 에 material 적용
